import { dPrice, grandTotal, getTotal, nPrice } from "./billUtils";

export const pdata = [
  {
    pid: "B00",
    name: "Texas heatwave",
    price: 439,
    qty: 1,
    discount: "15%",
    discounted_price: dPrice(439, 15),
    final_price: nPrice(439, dPrice(439, 15)),
  },
  {
    pid: "B01",
    name: "El Diablo",
    price: 419,
    qty: 1,
    discount: "15%",
    discounted_price: dPrice(419, 15),
    final_price: nPrice(419, dPrice(419, 15)),
  },
  {
    pid: "B02",
    name: "Philly Cheese Steak",
    price: 365,
    qty: 1,
    discount: "15%",
    discounted_price: dPrice(365, 15),
    final_price: nPrice(365, dPrice(365, 15)),
  },
  {
    pid: "B03",
    name: "El Junior",
    price: 249,
    qty: 1,
    discount: "15%",
    discounted_price: dPrice(249, 15),
    final_price: nPrice(249, dPrice(249, 15)),
  },
  {
    pid: "B04",
    name: "Philly Cheese Steak",
    price: 365,
    qty: 1,
    discount: "15%",
    discounted_price: dPrice(365, 15),
    final_price: nPrice(365, dPrice(365, 15)),
  },
  {
    pid: "B05",
    name: "Crazy Compton",
    price: 349,
    qty: 1,
    discount: "15%",
    discounted_price: dPrice(349, 15),
    final_price: nPrice(349, dPrice(349, 15)),
  },
  {
    pid: "B06",
    name: "Enorme",
    price: 399,
    qty: 1,
    discount: "15%",
    discounted_price: dPrice(399, 15),
    final_price: nPrice(399, dPrice(399, 15)),
  },
  {
    pid: "B07",
    name: "Quesadilla",
    price: 329,
    qty: 1,
    discount: "15%",
    discounted_price: dPrice(329, 15),
    final_price: nPrice(329, dPrice(329, 15)),
  },
  {
    pid: "B08",
    name: "Tacos (3)",
    price: 285,
    qty: 1,
    discount: "15%",
    discounted_price: dPrice(285, 15),
    final_price: nPrice(285, dPrice(285, 15)),
  },
  {
    pid: "B09",
    name: "Picante Fries",
    price: 199,
    qty: 1,
    discount: "0%",
    discounted_price: 199,
    final_price: 199,
  },
  {
    pid: "B10",
    name: "French Fries",
    price: 69,
    qty: 1,
    discount: "0%",
    discounted_price: 69,
    final_price: 69,
  },
  {
    pid: "B11",
    name: "Soda",
    price: 50,
    qty: 1,
    discount: "0%",
    discounted_price: 50,
    final_price: 50,
  },
  {
    pid: "B12",
    name: "Water",
    price: 0,
    qty: 1,
    discount: "15%",
    discounted_price: 50,
    final_price: 50,
  },
];
