import Head from "next/head";

import styles from "../styles/Home.module.css";
import _ from "lodash";
import { pdata } from "../lib/productData";
import SelectMenu from "../components/layouts/SelectMenu";
import MakeMenu from "../components/layouts/MakeMenu";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Picante POS</title>
        <meta name="description" content="Generated by Picante POS" />
        <link rel="icon" href="/logo.jpeg" />
      </Head>

      <div className="mx-auto flex items-start justify-between">
        <MakeMenu />

        <div className="h-screen overflow-scroll">
          <SelectMenu />
        </div>
      </div>
    </div>
  );
}
