import Head from "next/head";
import Image from "next/image";
import MakeMenu from "../components/layouts/MakeMenu";
import OrderEntry from "../components/layouts/OrderEntry";
import Receipt from "../components/Receipt";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1 className="text-4xl p-3 mx-auto font-bold">POS</h1>
        <Receipt />
        <MakeMenu />
      </div>
    </div>
  );
}
